#pragma once

// Default to RSS unless overridden by a compile definition:
// -DPKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY=linear
// -DPKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY=rss
#ifndef PKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY
#define PKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY rss
#endif

#define PKR_UNITS_DETAIL_STRATEGY_VALUE(x) PKR_UNITS_DETAIL_STRATEGY_VALUE_IMPL(x)
#define PKR_UNITS_DETAIL_STRATEGY_VALUE_IMPL(x) PKR_UNITS_DETAIL_STRATEGY_VALUE_##x
#define PKR_UNITS_DETAIL_STRATEGY_VALUE_rss 1
#define PKR_UNITS_DETAIL_STRATEGY_VALUE_linear 2

#if PKR_UNITS_DETAIL_STRATEGY_VALUE(PKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY) == 1
#include <pkr_units/measurements/measurement_math_rss.h>
#elif PKR_UNITS_DETAIL_STRATEGY_VALUE(PKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY) == 2
#include <pkr_units/measurements/measurement_math_linear.h>
#else
#error "Unknown PKR_UNITS_MEASUREMENT_UNCERTAINTY_STRATEGY. Use 'rss' or 'linear'."
#endif

#undef PKR_UNITS_DETAIL_STRATEGY_VALUE
#undef PKR_UNITS_DETAIL_STRATEGY_VALUE_IMPL
#undef PKR_UNITS_DETAIL_STRATEGY_VALUE_rss
#undef PKR_UNITS_DETAIL_STRATEGY_VALUE_linear
