#!/usr/bin/env python3
"""Generate an umbrella header including all headers under sdk/include/pkr_units.

Usage:
  python tools/generate_tests_umbrella.py --out tests/tools/_all_sdk_headers.h

The script writes the header only if its contents would change (to avoid noisy rebuilds).
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1] / 'sdk' / 'include' / 'pkr_units'


def generate(out_path: Path):
    entries = []
    for path in ROOT.rglob('*.h'):
        rel = path.relative_to(ROOT).as_posix()
        # skip removed/legacy umbrella header
        if rel == 'units/computer_science/count.h':
            continue
        entries.append(rel)
    entries.sort()

    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append('// Auto-generated umbrella header for tests. Do not edit.')
    lines.append('// Generated by tools/generate_tests_umbrella.py')
    lines.append('')
    lines.append('#ifndef PKR_UNITS_ALL_SDK_HEADERS_H')
    lines.append('#define PKR_UNITS_ALL_SDK_HEADERS_H')
    lines.append('')
    lines.append('// Standard library includes')
    lines.append('#include <complex>')
    lines.append('')
    lines.append('// Individual headers follow in deterministic sorted order')
    for rel in entries:
        lines.append(f'#include <pkr_units/{rel}>')
    lines.append('')
    lines.append('#endif // PKR_UNITS_ALL_SDK_HEADERS_H')
    lines.append('')

    new_text = '\n'.join(lines)
    if out_path.exists():
        old_text = out_path.read_text(encoding='utf-8')
        if old_text == new_text:
            print(f'No changes for {out_path}')
            return
    out_path.write_text(new_text, encoding='utf-8')
    print(f'Wrote {out_path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate umbrella header for tests')
    parser.add_argument('--out', type=Path, required=True, help='Output path for the umbrella header')
    args = parser.parse_args()
    generate(args.out)
